---
title: "TidyTuesday Week 15: US Egg Production"
date: 2023-05-14
output: html_document
---


```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

# install.packages(c("tidyverse", "tidytuesdayR"))

library(tidyverse)
library(tidytuesdayR)

```

# Get the data

First, let's grab the data from the GitHub rep and save it in CSVs.

```{r Download, eval=FALSE}

tt <- tt_load_gh("2023-04-11")

tt_download_file(tt, "egg-production.csv") |> 
  write_csv(here::here("20230411/data/egg-production.csv"))

tt_download_file(tt, "cage-free-percentages.csv") |> 
  write_csv(here::here("20230411/data/cage-free-percentages.csv"))
```

# Exploratory Analysis

Now let's begin by familiarising ourselves with this week's data. First we'll read in the CSV files.

```{r Load}
plots <- read_csv(here::here("20230502/data/plots.csv"))
surveys <- read_csv(here::here("20230502/data/surveys.csv"))
species <- read_csv(here::here("20230502/data/species.csv"))
```


```{r glimpse_childcare_costs}
glimpse(plots)
```


```{r glimpse_counties}
glimpse(species)
```

```{r glimpse_counties}
glimpse(surveys)
```
