---
title: "TidyTuesday Week 19: Childcare Costs"
date: 2023-05-14
output: html_document
---


```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

library(tidyverse)
library(tidytuesdayR)

```

# Get the data

First, let's grab the data from the GitHub rep and save it in CSVs.

```{r Download, eval=FALSE}

tt <- tt_load_gh("2023-05-09")

tt_download_file(tt, "childcare_costs.csv") |> 
  write_csv(here::here("20230509/data/childcare_costs.csv"))

tt_download_file(tt, "counties.csv") |> 
  write_csv(here::here("20230509/data/counties.csv"))

```

# Exploratory Analysis

Now let's begin by familiarising ourselves with this week's data. First we'll read in the CSV files.

```{r Load}
childcare_costs <- read_csv(here::here("20230509/data/childcare_costs.csv"))
counties <- read_csv(here::here("20230509/data/counties.csv"))
```

What does the childcare_costs.csv file look like?

```{r glimpse_childcare_costs}
glimpse(childcare_costs)
```

And what about counties.csv?

```{r glimpse_counties}
glimpse(counties)
```

